spring:
  application:
    name: customer-service   # ? must be lowercase and match your file name in Git repo (customer-service.yml)
  config:
    import: optional:configserver:http://localhost:8888  # ? fetches config from Config Server

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost       # force localhost
    ip-address: 127.0.0.1     # force IP to localhost
    prefer-ip-address: true    # register with IP
    instance-id: customer-service:${server.port}
    metadata-map:
      hostname: localhost