server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/YembuluruVenkatesh/ConfigServer.git
          clone-on-start: true
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/   # use container name
  instance:
    prefer-ip-address: true
    instance-id: config-server:${server.port}
