spring:
  application:
    name: order-service  # 👈 must be lowercase and match your file name in Git repo (order-service.yml)
  config:
    import: optional:configserver:http://localhost:8888  # 👈 fetches config from Config Server
  cloud:
    client:
      hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost       # force localhost
    ip-address: 127.0.0.1     # force IP to localhost
    prefer-ip-address: true    # register with IP
    instance-id: order-service:${server.port}
    metadata-map:
      hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      orderServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 3
        waitDuration: 1s




